### ISSUE TITLE
Nakamoto: PoX & Other Clarity Contracts To Update Checklist

### ISSUE THREAD

**Issue by setzeus** [stacks-network/stacks-blockchain#3877]
Opening this issue for the Clarity WG to research, note, & track existing Clarity contracts that need to be updated prior to the Nakamoto hardfork. As of now, the core focus is updating the PoX-3 contract from the existing sbtc-mini-stacking-pool contract.

Properties of Stacking Pool To Fold Into PoX-4:
- [ ] - Pre-registration (will **not** persist)
- [ ] - Registration (will **not** persist)
- [ ] - Voting
- [ ] - Verifying hand-off
- [ ] - Penalty #1: Fail to register new wallet (will **not** persist)
- [ ] - Penalty #2: Fail to transfer peg-balance (will **not** persist)
- [ ] - Penalty #3: Fail to distribute PoX rewards (will **not** persist)
- [ ] - Penalty #4: Fail to vote on outstanding (will **not** persist)

**Additional Existing Network / Boot Clarity Contracts**
Last, I’d like to leave the open question of additional Clarity contracts that requires an update for sBTC/Nakamoto. Outside of the PoX contract, is there any other contract that we didn’t work on in mini but is needed in production?

**Comment by setzeus** [comment]
Ahhh, due to permission can't add labels or assign so going to tag Clarity WG participants for visibility: @MarvinJanssen @friedger @jo-tm @friendsferdinand

**Comment by will-at-stacks** [comment]
> 

@setzeus do you have the permissions you need now?

**Comment by setzeus** [comment]
I don't think I can edit labels or assign? But the right label it there atm so np.

As a WG we're still unsure if we're primarily going to work in /stacks-blockchain or in /sbtc.

**Comment by jcnelson** [comment]
You should work under `/stacks-blockchain`.  The sBTC smart contracts are going to live in `stackslib/src/chainstate/stacks/boot/`
