### ISSUE TITLE
Nakamoto: sBTC-Mini Standalone Persistence Checklist

### ISSUE THREAD

**Issue by setzeus** [stacks-network/stacks-blockchain#3878]
Opening this issue for the Clarity WG to keep track of transfer items during Sprint 4. We specifically need to figure out which of the current sBTC-Mini contracts will persist into the Nakamoto hardfork. There are two sister issues because I think each issue/question is worth discussing on it’s own & may vary in importance to different working groups. 

This issue specifically revolves around which of the current sBTC-Mini contracts will persist in Nakamoto as stand-alone contracts? Not folded into boot contracts (this is covered in #441)

**Status Overview**
Below is a checklist of the existing contracts found in our existing sBTC-Mini repo:
- [x] stacking-pool (will **not** persist, discussed in #3877)
- [x] pox-3 (will **not** persist, discussed in #3877)
- [ ] clarity-bitcoin
- [ ] sbtc-btc-tx-helper 
- [ ] sbtc-controller
- [ ] sbtc-deposit-processor
- [ ] sbtc-withdrawal-processor
- [ ] sbtc-hand-off-processor
- [ ] sbtc-registry
- [ ] sbtc-testnet-debug-controller
- [ ] sbtc-token
- [ ] sbtc-stx-helper

**Open Questions**
These are known unknowns that I primarily have so I’m stating them here before making an issue in case anyone in the sBTC-Mini group has an answer already:

1. What decision are we making re: the Clarity-Bitcoin contract(s)?
Is the idea still to have two versions of this? One optimized strictly for sBTC & one general?

2. Are all the Bitcoin processor contracts still necessary?
It isn't clear (at least to me) what Bitcoin verification the nodes will take care of in Nakamoto vs. the contracts - do we still need all three processor-contracts? Or is that work off-loaded to nodes?

3. Do we still keep the two protocol-state contracts?
Also unclear (again, to me), is the role of the sbtc-controller & sbtc-registry contracts. Are they still both independently needed in Nakamoto? Can the sbtc-registry state be stored in StackerDB or somewhere else? (don't mean to duplicate conversation already happening on sbtc-registry [here](https://github.com/Trust-Machines/stacks-sbtc/issues/682))

**Comment by setzeus** [comment]
Also tagging for visibility: @MarvinJanssen @friedger @jo-tm @friendsferdinand

**Comment by will-at-stacks** [comment]
should this be retitled to `sBTC-Alpha-Romeo` checklist?
